Improve Docker image
We no longer want to bundle our Docker image with MongoDB but instead want to
connect to a MongoDB that lives outside of our container and is maintained by
the end user.

[skip ci]

diff --git a/.docker/Dockerfile b/.docker/Dockerfile
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -1,4 +1,4 @@
-FROM mongo:3.4.20
+FROM node:8.9.4
 
 MAINTAINER 4Minitz-Team <4minitz@gmx.de>
 
@@ -18,51 +18,33 @@ LABEL org.label-schema.build-date=$BUILD_DATE \
       org.label-schema.schema-version="1.0"
 
 
+#### MongoDB connection configuration
+#### This will fail since we no longer bundle a MongoDB
+#### with our releases. It is expected that this is passed
+#### in by the admin when instantiating the container.
+ENV MONGO_URL mongodb://admin:admin@localhost/4minitz
+
 #### Install Node.js
 ENV NPM_CONFIG_LOGLEVEL info
-ENV NODE_VERSION 8.9.4
 
 #### In case you get this with a new node version:
 ####      Can't check signature: public key not found??
 #### then see
 ####      https://github.com/nodejs/node#release-team
-RUN groupadd --gid 1000 node \
-    && useradd --uid 1000 --gid node --shell /bin/bash --create-home node \
-    && set -ex \
-    && for key in \
-        56730D5401028683275BD23C23EFEFE93C4CFFFE \
-        71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
-        77984A986EBC2AA786BC0F66B01FBB92821C587A \
-        94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
-        B9AE9905FFD7803F25714661B63B535A4C206CA9 \
-        C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
-        DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
-        FD3A5288F042B6850C66B31F09FE44734EB7990E \
-        0C49F3730359A14518585931BC711F9BA15703C6 \
-      ; do \
-            gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" || \
-            gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" || \
-            gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
-        done \
-    \
+RUN set -ex \
     && apt-get update && apt-get install -y --no-install-recommends \
         ca-certificates \
         curl \
+        ghostscript \
         git \
+        nano \
         openssh-client \
         wget \
+        wkhtmltopdf \
+        xauth \
+        xvfb \
         xz-utils \
-        nano \
-        wkhtmltopdf xauth xvfb ghostscript=9.26~dfsg+0-0ubuntu0.16.04.8 \
     && rm -rf /var/lib/apt/lists/* \
-    \
-    && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
-    && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
-    && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
-    && grep " node-v$NODE_VERSION-linux-x64.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
-    && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 \
-    && rm "node-v$NODE_VERSION-linux-x64.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
-    && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
     \
     && cp /usr/share/ghostscript/9.26/lib/PDFA_def.ps / \
     && cp /usr/share/ghostscript/9.26/iccprofiles/srgb.icc / \
@@ -74,6 +56,8 @@ RUN groupadd --gid 1000 node \
 COPY 4minitz_bin /4minitz_bin
 COPY 4minitz.sh /
 COPY 4minitz_settings.json /
+
+VOLUME /4minitz_storage
 
 # Important: do NOT use: 'CMD ./4minitz.sh' - this will result in
 # a /bin/sh child process /bin/bash with a PID!=1 - so, the SIGINT
